import type {
  DemoChannel,
  DemoCollection,
  DemoProject,
  DemoRepositoryCandidate,
  DemoSighting,
} from "./types";

const manuVideo = {
  channel: "ManuAGI",
  channelHandle: "@ManuAGI",
  videoId: "KITOm0HitpY",
  videoTitle: "20 AI tools and products worth knowing",
  publishedAt: "Jul 21, 2026",
};

function sighting(
  id: string,
  timestamp: string,
  timestampSeconds: number,
  name: string,
  url: string,
  overrides: Partial<DemoSighting> = {},
): DemoSighting {
  return {
    id,
    ...manuVideo,
    timestamp,
    timestampSeconds,
    rawSegment: `${timestamp} - ${name}: ${url}?ref=manuagi`,
    originalUrl: `${url}?ref=manuagi`,
    ...overrides,
  };
}

export const demoProjects: DemoProject[] = [
  {
    id: "understand-anything",
    name: "Understand Anything",
    description:
      "Turn a codebase into a navigable knowledge graph with linked explanations, dependency paths, and source-aware exploration.",
    domain: "github.com/Egonex-AI/Understand-Anything",
    primaryUrl: "https://github.com/Egonex-AI/Understand-Anything",
    repositoryUrl: "https://github.com/Egonex-AI/Understand-Anything",
    repositoryState: "verified",
    repositoryLabel: "Egonex-AI/Understand-Anything",
    language: "TypeScript",
    license: "Apache-2.0",
    stars: 12800,
    topics: ["code-graph", "knowledge", "developer-tools"],
    activity: "today",
    activityLabel: "updated 3h ago",
    seenAt: "Today, 12:14",
    sightingCount: 4,
    isNew: true,
    isImpressive: true,
    collectionIds: ["reverse-engineering", "deep-research"],
    accent: "#6546c7",
    initials: "UA",
    note: "Study the graph-building boundary before adding repository analysis to Hardware.",
    sightings: [
      sighting(
        "ua-s1",
        "04:48",
        288,
        "Understand Anything",
        "https://github.com/Egonex-AI/Understand-Anything",
        {
          channel: "AI Jason",
          channelHandle: "@AIJasonZ",
          videoId: "repo-intelligence-01",
          videoTitle: "Open-source tools changing how we read code",
          publishedAt: "Jul 22, 2026",
        },
      ),
      sighting(
        "ua-s2",
        "09:12",
        552,
        "Understand Anything",
        "https://github.com/Egonex-AI/Understand-Anything",
        {
          channel: "World of AI",
          channelHandle: "@WorldofAI",
          videoId: "repo-intelligence-02",
          videoTitle: "The week in open-source AI",
          publishedAt: "Jul 19, 2026",
        },
      ),
    ],
  },
  {
    id: "repobase",
    name: "Repobase",
    description:
      "A local-first repository intelligence layer for indexing source trees and retrieving the code context that matters.",
    domain: "github.com/fernandoabolafio/repobase",
    primaryUrl: "https://github.com/fernandoabolafio/repobase",
    repositoryUrl: "https://github.com/fernandoabolafio/repobase",
    repositoryState: "verified",
    repositoryLabel: "fernandoabolafio/repobase",
    language: "Python",
    license: "MIT",
    stars: 6400,
    topics: ["repository", "retrieval", "code-search"],
    activity: "week",
    activityLabel: "updated 2d ago",
    seenAt: "Today, 10:42",
    sightingCount: 3,
    isNew: true,
    isImpressive: true,
    collectionIds: ["reverse-engineering"],
    accent: "#245fc5",
    initials: "RB",
    sightings: [
      sighting(
        "rb-s1",
        "07:03",
        423,
        "Repobase",
        "https://github.com/fernandoabolafio/repobase",
        {
          channel: "World of AI",
          channelHandle: "@WorldofAI",
          videoId: "open-source-roundup-20",
          videoTitle: "20 open-source projects you missed",
          publishedAt: "Jul 22, 2026",
        },
      ),
    ],
  },
  {
    id: "in-parallel-mcp",
    name: "In Parallel MCP",
    description:
      "A research MCP server that runs independent investigations in parallel and returns structured, source-linked findings.",
    domain: "in-parallel.com/mcp",
    primaryUrl: "https://www.in-parallel.com/mcp/",
    repositoryState: "candidate",
    repositoryLabel: "in-parallel/mcp-server",
    language: "TypeScript",
    license: "Unknown",
    topics: ["mcp", "research", "parallel-agents"],
    activity: "today",
    activityLabel: "candidate found 18m ago",
    seenAt: "Today, 09:51",
    sightingCount: 2,
    isNew: true,
    isImpressive: true,
    collectionIds: ["agent-patterns", "deep-research"],
    accent: "#b43f2d",
    initials: "IP",
    sightings: [
      sighting(
        "ip-s1",
        "05:03",
        303,
        "In Parallel MCP",
        "https://www.in-parallel.com/mcp/",
      ),
    ],
  },
  {
    id: "albato-ai",
    name: "Albato AI",
    description:
      "Connect applications and automate multi-step business workflows with a visual integration builder and API triggers.",
    domain: "albato.com/automate",
    primaryUrl: "https://albato.com/automate",
    repositoryState: "not-found",
    topics: ["automation", "integrations", "workflows"],
    activity: "month",
    activityLabel: "metadata checked today",
    seenAt: "Yesterday, 17:22",
    sightingCount: 1,
    isNew: true,
    collectionIds: ["automation"],
    accent: "#a84310",
    initials: "AA",
    sightings: [sighting("aa-s1", "00:55", 55, "Albato AI", "https://albato.com/automate")],
  },
  {
    id: "river",
    name: "River",
    description:
      "A go-to-market workspace for researching accounts, orchestrating signals, and turning structured context into action.",
    domain: "rivergtm.com",
    primaryUrl: "https://www.rivergtm.com/",
    repositoryState: "not-found",
    topics: ["gtm", "research", "sales"],
    activity: "month",
    activityLabel: "metadata checked today",
    seenAt: "Yesterday, 17:18",
    sightingCount: 2,
    collectionIds: ["automation"],
    accent: "#12685f",
    initials: "RV",
    sightings: [sighting("rv-s1", "02:38", 158, "River", "https://www.rivergtm.com/")],
  },
  {
    id: "graft-ai",
    name: "Graft AI",
    description:
      "A focused agent workspace for building repeatable workflows around research, drafting, and operational handoffs.",
    domain: "graft.axcelner.com",
    primaryUrl: "https://graft.axcelner.com/",
    repositoryState: "candidate",
    repositoryLabel: "axcelner/graft",
    language: "TypeScript",
    license: "Unknown",
    topics: ["agents", "workflows", "productivity"],
    activity: "week",
    activityLabel: "candidate found 1h ago",
    seenAt: "Yesterday, 17:12",
    sightingCount: 1,
    collectionIds: ["agent-patterns"],
    accent: "#8a551f",
    initials: "GA",
    sightings: [sighting("ga-s1", "05:55", 355, "Graft AI", "https://graft.axcelner.com/")],
  },
  {
    id: "agently",
    name: "Agently",
    description:
      "An open developer framework for composing agent capabilities, tool calls, and reusable execution workflows.",
    domain: "agently.dev",
    primaryUrl: "https://agently.dev/",
    repositoryUrl: "https://github.com/AgentEra/Agently",
    repositoryState: "verified",
    repositoryLabel: "AgentEra/Agently",
    language: "Python",
    license: "Apache-2.0",
    stars: 3700,
    topics: ["agents", "framework", "python"],
    activity: "week",
    activityLabel: "updated 4d ago",
    seenAt: "Jul 21, 16:37",
    sightingCount: 5,
    collectionIds: ["agent-patterns"],
    accent: "#0f6874",
    initials: "AG",
    sightings: [sighting("ag-s1", "15:02", 902, "Agently", "https://agently.dev/")],
  },
  {
    id: "yagni",
    name: "YAGNI",
    description:
      "A minimal planning tool built around making the next useful decision visible without accumulating process overhead.",
    domain: "yagni.app",
    primaryUrl: "https://yagni.app/",
    repositoryState: "not-found",
    topics: ["planning", "focus", "productivity"],
    activity: "quiet",
    activityLabel: "metadata checked today",
    seenAt: "Jul 21, 16:21",
    sightingCount: 1,
    collectionIds: [],
    accent: "#615b50",
    initials: "YG",
    sightings: [sighting("yg-s1", "16:37", 997, "YAGNI", "https://yagni.app/")],
  },
  {
    id: "drdroid",
    name: "DrDroid Alert Grouping",
    description:
      "Incident tooling that groups related alerts, preserves operational context, and helps teams reduce noisy investigations.",
    domain: "drdroid.io",
    primaryUrl: "https://drdroid.io/",
    repositoryState: "verified",
    repositoryUrl: "https://github.com/DrDroidLab/playbooks",
    repositoryLabel: "DrDroidLab/playbooks",
    language: "Python",
    license: "Apache-2.0",
    stars: 1200,
    topics: ["observability", "incidents", "operations"],
    activity: "week",
    activityLabel: "updated 5d ago",
    seenAt: "Jul 21, 15:54",
    sightingCount: 2,
    collectionIds: ["infrastructure"],
    accent: "#405b9a",
    initials: "DD",
    sightings: [sighting("dd-s1", "11:32", 692, "Alert Grouping by DrDroid", "https://drdroid.io/")],
  },
  {
    id: "crustdata-recruiter",
    name: "Crustdata Recruiter",
    description:
      "Company and people data workflows designed to support structured recruiting research and candidate discovery.",
    domain: "crustdata.com/solutions/claude-for-recruiting",
    primaryUrl: "https://crustdata.com/solutions/claude-for-recruiting",
    repositoryState: "not-found",
    topics: ["data", "recruiting", "research"],
    activity: "month",
    activityLabel: "metadata checked yesterday",
    seenAt: "Jul 21, 15:49",
    sightingCount: 1,
    collectionIds: ["deep-research"],
    accent: "#7244ae",
    initials: "CR",
    sightings: [
      sighting(
        "cr-s1",
        "15:50",
        950,
        "Crustdata Recruiter",
        "https://crustdata.com/solutions/claude-for-recruiting",
      ),
    ],
  },
];

export const demoCollections: DemoCollection[] = [
  {
    id: "reverse-engineering",
    name: "Reverse engineering",
    description: "Code intelligence, graphing, retrieval, and architecture-understanding systems.",
    visibility: "private",
    projectIds: ["understand-anything", "repobase"],
    updatedAt: "12 minutes ago",
    accent: "#6546c7",
  },
  {
    id: "agent-patterns",
    name: "Agent patterns",
    description: "Useful orchestration, tool-use, parallelism, and execution models.",
    visibility: "workspace",
    projectIds: ["in-parallel-mcp", "graft-ai", "agently"],
    updatedAt: "Today, 09:54",
    accent: "#b43f2d",
  },
  {
    id: "deep-research",
    name: "Deep research",
    description: "Research workflows where citations, provenance, and context boundaries matter.",
    visibility: "private",
    projectIds: ["understand-anything", "in-parallel-mcp", "crustdata-recruiter"],
    updatedAt: "Yesterday",
    accent: "#245fc5",
  },
  {
    id: "automation",
    name: "Automation systems",
    description: "Integration and operational workflow ideas worth revisiting.",
    visibility: "private",
    projectIds: ["albato-ai", "river"],
    updatedAt: "Jul 20",
    accent: "#12685f",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    description: "Operations, observability, deployment, and reliability tooling.",
    visibility: "workspace",
    projectIds: ["drdroid"],
    updatedAt: "Jul 19",
    accent: "#405b9a",
  },
];

export const demoChannels: DemoChannel[] = [
  {
    id: "manuagi",
    name: "ManuAGI",
    handle: "@ManuAGI",
    avatar: "MA",
    status: "healthy",
    videos: 184,
    projects: 1432,
    lastSync: "18 minutes ago",
    nextSync: "in 5h 42m",
  },
  {
    id: "world-of-ai",
    name: "World of AI",
    handle: "@WorldofAI",
    avatar: "WA",
    status: "syncing",
    videos: 327,
    projects: 2084,
    progress: 72,
    progressLabel: "236 of 327 videos",
    lastSync: "syncing now",
    nextSync: "after this run",
  },
  {
    id: "ai-jason",
    name: "AI Jason",
    handle: "@AIJasonZ",
    avatar: "AJ",
    status: "healthy",
    videos: 96,
    projects: 684,
    lastSync: "2 hours ago",
    nextSync: "in 3h 58m",
  },
  {
    id: "matt-wolfe",
    name: "Matt Wolfe",
    handle: "@mreflow",
    avatar: "MW",
    status: "attention",
    videos: 211,
    projects: 1189,
    progress: 94,
    progressLabel: "2 videos need retry",
    lastSync: "5 hours ago",
    nextSync: "manual retry available",
  },
];

export const demoCandidates: DemoRepositoryCandidate[] = [
  {
    id: "candidate-in-parallel",
    projectId: "in-parallel-mcp",
    projectName: "In Parallel MCP",
    repository: "in-parallel/mcp-server",
    score: 86,
    evidence: ["Exact product name", "Website links to GitHub organization", "Matching TypeScript package"],
    discoveredAt: "18 minutes ago",
  },
  {
    id: "candidate-graft",
    projectId: "graft-ai",
    projectName: "Graft AI",
    repository: "axcelner/graft",
    score: 74,
    evidence: ["Matching domain owner", "Repository README names Graft", "Recent product activity"],
    discoveredAt: "1 hour ago",
  },
];

export function getDemoProject(id: string) {
  return demoProjects.find((project) => project.id === id);
}

export function getDemoCollection(id: string) {
  return demoCollections.find((collection) => collection.id === id);
}
